apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-configuration
  labels:
    app: postgres
data:
  POSTGRES_DB: aWFjLXBvc3RncmVzcWwK
  POSTGRES_USER: YWRtaW4K
  POSTGRES_PASSWORD: UEBzc3cwcmQyMDIyCg==
  PGDATABASE: aWFjLXBvc3RncmVzcWwK
  PGUSER: YWRtaW4K
  PGPASSWORD: UEBzc3cwcmQyMDIyCg==