apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnidb
  labels:
    app: omnidb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omnidb
  template:
    metadata:
      labels:
        app: omnidb
    spec:
      initContainers:
      - name: init
        image: busybox:1.28
        command: ['sh', '-c', "chmod 777 -R /etc/omnidb"]
        volumeMounts:
        - name: pv-data
          mountPath: /etc/omnidb
          subPath: omnidbnew2       
      containers:
      - name: omnidb
        image: taivokasper/omnidb
        env:
          - name: "GOOGLE_APPLICATION_CREDENTIALS"
            value: "/var/run/secret/cloud.google.com/service-account.json"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pv-data
          mountPath: /home/omnidb/.omnidb
          subPath: omnidbnew1
        - name: pv-config
          mountPath: /etc/omnidb
          subPath: omnidbnew2
        - name: service-account
          mountPath: /var/run/secret/cloud.google.com
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: hicham-claim-omnidb
          readOnly: false
      - name: pv-config
        persistentVolumeClaim:
          claimName: hicham-claim-omnidb2
          readOnly: false
      - name: service-account
        secret:
          secretName: my-app-sa-key