apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnidb
  labels:
    app: omnidb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omnidb
  template:
    metadata:
      labels:
        app: omnidb
    spec:
      containers:
      - name: omnidb
        image: omnidbteam/omnidb
        ports:
        - containerPort: 8000