apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnidb
  labels:
    app: omnidb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omnidb
  template:
    metadata:
      labels:
        app: omnidb
    spec:
      containers:
      - name: omnidb
        image: taivokasper/omnidb
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: pv-data
          mountPath: /etc/omnidb
          subPath: omnidb
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: hicham-claim-omnidb
          readOnly: false