apiVersion: v1
kind: PersistentVolume
metadata:
  name: hicham-share-omnidb
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /share1
    server: 10.171.170.10
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hicham-claim-omnidb
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: hicham-share-omnidb
  resources:
    requests:
      storage: 10Gi
      
      
