apiVersion: v1
kind: PersistentVolume
metadata:
  name: hicham-share-omnidb
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /share2
    server: 10.175.161.178
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hicham-claim-omnidb
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: hicham-share-omnidb
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: hicham-share-omnidb2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /share2
    server: 10.175.161.178
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hicham-claim-omnidb2
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: hicham-share-omnidb2
  resources:
    requests:
      storage: 10Gi
      
      
